aplikacja_todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
]

base/urls.py
from django.urls import path
from .views import TaskList, TaskDetail, TaskCreate, TaskUpdate, DeleteView, CustomLoginView, RegisterPage
from django.contrib.auth.views import LogoutView

urlpatterns =[
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('',TaskList.as_view(), name='tasks'),
    path('task/<int:pk>',TaskDetail.as_view(), name='task'),
    path('task-create/',TaskCreate.as_view(), name='task-create'),
    path('task-update/<int:pk>', TaskUpdate.as_view(), name='task-update'),
    path('task-delete/<int:pk>', DeleteView.as_view(), name='task-delete'),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '' if self.title is None else self.title

    class Meta:
        ordering = ['complete']

base/views.py
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy

from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .models import Task


# Create your views here.

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('tasks')

class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith=search_input)
        context['search_input'] = search_input
        return context


class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('tasks')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete']
    success_url = reverse_lazy('tasks')

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')

base/templates/base/login.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}


<div class="container-form">
    <div class="container-login">
        <h1>WebOrganizer</h1>
        <h2 class="login-header-h1">Zaloguj</h2>
        <form method="POST">
            {% csrf_token %}
            <h4>Użytkownik:</h4>
            <p>
                <input class="login-input" type="text" name="username" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
            </p>
            <h4>Hasło:</h4>
            <p>
                <input class="login-input" type="password" name="password" autocomplete="current-password" required id="id_password">
            </p>
            <input type="submit" class="login-button" value="Zaloguj">
        </form>
        <p>Nie masz konta? <a href="{% url 'register' %}">Zarejestruj się</a></p>
    </div>
</div>
<script src="{% static '/js/fade-login.js' %}"></script>
{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Organizer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

</head>
<body>
  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

</body>

</html>

base/templates/base/register.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

<div class="container-register">
    <h1 class="login-header-h1">Rejestracja</h1>
    <form method="POST">
    {% csrf_token %}
        <p>
        <h3>Nazwa użytkownika:</h3>
        <input type="text" class="register-input" name="username" maxlength="150" autocapitalize="none" autocomplete="username" required id="id_username">
        <p>Wymagane 150 lub mniej znaków. Jedynie litery, cyfry i @/./+/-/_.</p>
        </p>
        <p>
        <h3>Hasło:</h3>
        <input type="password" class="register-input" name="password1" autocomplete="new-password" required id="id_password1">
        <p><ul><li>Twoje hasło nie może być zbyt podobne do twoich innych danych osobistych.</li>
        <li>Twoje hasło musi zawierać co najmniej 8 znaków.</li>
        <li>Twoje hasło nie może być powszechnie używanym hasłem.</li>
        <li>Twoje hasło nie może składać się tylko z cyfr.</li></ul></p>
        </p>
        <p>
        <h3>Potwierdzenie hasła:</h3>
        <input type="password" class="register-input" name="password2" autocomplete="new-password" required id="id_password2">
        <p>Wprowadź to samo hasło ponownie, dla weryfikacji.</p>
        </p>
        <div class="center">
            <input type="submit"  class="login-button" value="Zarejestruj">
            <p>Masz już konto? <a href="{% url 'login' %}">Zaloguj się</a></p>
        </div>
</form>
</div>
<script src="{% static '/js/fade-register.js' %}"></script>
{% endblock content %}

base/templates/base/task.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<div class="container-task">
    <div class="task-info">
        <h1>Zadanie:</h1>
        <div class="description">
            <p> {{task}}</p>
        </div>
        <hr>
        <h2>Utworzono: </h2>
        <p>{{task.created}}</p>
        <hr>
        <h3>Opis zadania:</h3>
        <div class="description">
            <p>{{task.description}}</p>
        </div>
        <div class="center">
            <a href="{% url 'tasks' %}">Powrót</a>
        </div>
    </div>
</div>
<script src="{% static '/js/fade-task.js' %}"></script>
{% endblock content %}

base/templates/base/task_confirm_delete.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<div class="delete-task">
    <div class="center">
        <form method="POST">
        {% csrf_token %}
        <p>Czy chcesz usunąć to zadanie? "{{task}}"</p>
        <input class="login-button" type="submit" value="Usuń"/>
    </form>
        <a href = "{% url 'tasks' %}">Powrót</a>
    </div>


</div>

<script src="{% static '/js/fade-delete.js' %}"></script>
{% endblock content %}

base/templates/base/task_form.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
<div class="task-form-div">
    <h1>Dodaj lub edytuj zadanie</h1>

    <form method="POST" action="">
        {%csrf_token%}
        <p>
            <h3>Tytuł:</h3>
            <input class="text-input" type="text" name="title" maxlength="200" id="id_title" value="{{task.title}}">
        </p>
        <p>
             <h3>Opis:</h3>
            <textarea class="textarea-input" name="description" cols="50" rows="10" id="id_description">{{task.description}}</textarea>
        </p>
        <p>
            <label for="id_complete">Ukończono:</label>
            {% if task.complete is True %}
                <input type="checkbox" name="complete" id="id_complete" checked>
            {% else %}
                <input type="checkbox" name="complete" id="id_complete">
            {% endif %}
        </p>
        <a href = "{% url 'tasks' %}">Powrót</a>
        <div class="center">
            <input class="login-button" type="submit" value="Zatwierdź">
        </div>
    </form>
</div>
<script src="{% static '/js/fade-task-create.js' %}"></script>
{% endblock content %}

base/templates/base/task_list.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}
{% if request.user.is_authenticated %}

<div class="task-list">
    <div class="header">
        <div>
            <h3>Witaj {{request.user|title}}!</h3>
            <p style="margin:0">Ilość niekompletnych zadań to: <i>{{count}}</i></p>
        </div>
        <div class="logout">
             <a href="{% url 'logout' %}">Wyloguj</a>
        </div>

    </div>
    {% else %}
        <a href="{% url 'login' %}">Zaloguj</a>
    {% endif %}

    <div class="search-add-wrapper" style="text-align: center;">
        <h3>Wyszukaj zadanie</h3>
        <form method="GET">
            <input class="search-input"  type="text" name="search-area" value="{{search_input}}">
            <input class="login-button"  type="submit" value="Szukaj">
        </form>
        <form action="{% url 'task-create' %}">
            <input class="create-button" type="submit" value="Utwórz nowe zadanie">
        </form>
    </div>
    <div class="task-itmes-wrapper">
        {% for task in tasks %}
            <div class="task-wrapper">
                {% if task.complete %}
                <div class="task-title">
                    <div class="task-complete-icon"></div>
                    <i><s><a a href="{% url 'task-update' task.id %}">{{task}}</a></s></i>
                </div>
                {%else%}
                <div class="task-title">
                    <div class="task-incomplete-icon"></div>
                    <a a href="{% url 'task-update' task.id %}">{{task}}</a>
                </div>

                {% endif %}
                <a class="delete-link" href="{% url 'task-delete' task.id %}">&#215;</a>
            </div>


        {% empty %}
            <h3 style="padding: 10px;">Brak zadań w organizerze!</h3>
        {% endfor %}
    </div>
</div>
<script src="{% static '/js/task-list.js' %}"></script>
{% endblock content %}